##源数据源信息，多个数据源使用;分开
source.data.mongodb.uri=mongodb://admin:123456@192.168.3.172:6001/admin?authSource=admin
##目标数据源
target.data.mongodb.uri=mongodb://root:123456@192.168.3.100:6004/admin?authSource=admin
##同步模式 all全量 allIncrement全量加增量 increment增量
sync_mode=allIncrement
##增量同步时，设置增量开始同步的时间。时间戳格式，单位s
increment.start.time=now
##在增量中每个数据源解析数据的线程
increment.parse.thread_num=5
##需要同步的表名单 使用正则表达式
filter.namespace.white=photon.*
##是否同步DDL
filter.ddl_enable=true
##同步的表，若已存在。是否删除
full_sync.collection_exist_drop=true
##是否创建索引
full_sync.create_index=background
##取数据的线程数
task.sourcesplit.thread.num=sys
##写数据的线程数
task.target.thread.num=sys
##缓存区个数
cache.size=5
##每个缓存区缓存批次数量
cache.num=30
##每个批次数据的大小
data.batch_size=2000